oem: "TECNO"
device: "TECNO-CM7"
android_version: "15"
build_tag: "AP3A.240905.015.A2"
model: "TECNO CAMON 40 Pro 5G"

variants:
  - variant: "Global"
    product: "CM7-OP"
    incremental: "145009"

  - variant: "Turkey"
    product: "CM7-TR"
    incremental: "145009"
