oem: "Infinix"
device: "Infinix-X6871"
android_version: "15"
build_tag: "AP3A.240905.015.A2"
model: "Infinix GT 20 Pro"

variants:
  - variant: "Global"
    product: "X6871-OP"
    incremental: "145015"

  - variant: "India"
    product: "X6871-IN"
    incremental: "145015"

  - variant: "Russia"
    product: "X6871-RU"
    incremental: "145015"
