oem: "Infinix"
device: "Infinix-X6852"
android_version: "15"
build_tag: "AP3A.240905.015.A2"
model: "Infinix NOTE 40 5G"

variants:
  - variant: "Global"
    product: "X6852-OP"
    incremental: "155004"

  - variant: "India"
    product: "X6852-IN"
    incremental: "155001"

  - variant: "Europe"
    product: "X6852-EU"
    incremental: "155005"
