# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys

oem: "TECNO"             # The company that made your device (e.g. Samsung)
product: "KJ5-OP"         # The product code. May be same as device code or model code.
device: "TECNO-KJ5"          # The device code. May be same as model code.
android_version: "13" # Only put in the major version number.
build_tag: "TP1A.220624.014"       # Example: RKQ1.211119.001
incremental: "250514V2052"     # Example: 2206131341
model: "TECNO SPARK 20"           # The model code. (e.g. SM-T380)
