oem: "TECNO"
device: "TECNO-AE11"
android_version: "14"
build_tag: "UP1A.231005.007"
model: "TECNO PHANTOM V Flip2 5G"

variants:
  - variant: "Global"
    product: "AE11-OP"
    incremental: "250818V4337"

  - variant: "Turkey"
    product: "AE11-TR"
    incremental: "250818V4337"

  - variant: "Russia"
    product: "AE11-RU"
    incremental: "250818V4337"

  - variant: "India"
    product: "AE11-IN"
    incremental: "250818V4337"
