oem: "TECNO"
device: "TECNO-CM5"
model: "TECNO CAMON 40 4G"

variants:
  - variant: "Global"
    android_version: "16"
    build_tag: "BP2A.250605.031.A3"
    product: "CM5-OP"
    incremental: "201200024"

  - variant: "Turkey"
    android_version: "15"
    build_tag: "AP3A.240905.015.A2"
    product: "CM5-TR"
    incremental: "1"

  - variant: "Russia"
    android_version: "15"
    build_tag: "AP3A.240905.015.A2"
    product: "CM5-RU"
    incremental: "1"
