oem: "TECNO"
device: "TECNO-LK7k"
android_version: "16"
build_tag: "BP2A.250605.031.A3"
model: "TECNO POVA Curve 2 5G"

variants:
  - variant: "Global"
    product: "LK7k-OP"
    incremental: "101400030"

  - variant: "India"
    product: "LK7k-IN"
    incremental: "101500150"
