oem: "Infinix"
device: "Infinix-X6873"
android_version: "15"
build_tag: "AP3A.240905.015.A2"
model: "Infinix GT 30 Pro"

variants:
  - variant: "Global"
    product: "X6873-OP"
    incremental: "145008"

  - variant: "India"
    product: "X6873-IN"
    incremental: "145008"

  - variant: "Russia"
    product: "X6873-RU"
    incremental: "145008"

  - variant: "Turkey"
    product: "X6873-TR"
    incremental: "145008"

  - variant: "Europe"
    product: "X6873-EU"
    incremental: "131015"
